# Generated by Django 3.1.6 on 2021-02-03 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignmentid', models.IntegerField(primary_key=True, serialize=False)),
                ('assignmentname', models.CharField(max_length=50)),
                ('assignment', models.FileField(default='no assignmnet yet', upload_to='media')),
                ('duedate', models.DateTimeField()),
                ('createddate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.IntegerField(primary_key=True, serialize=False)),
                ('coursedescription', models.CharField(max_length=500)),
                ('coursename', models.CharField(max_length=50)),
                ('userid', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('videolink', models.FileField(default='default_link', upload_to='')),
                ('createddate', models.DateTimeField()),
                ('imagelink', models.URLField(default='default_link')),
                ('duration', models.DateTimeField()),
                ('longdes', models.TextField()),
                ('coursetype', models.CharField(max_length=50)),
                ('assignto', models.CharField(max_length=200)),
                ('status', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='createQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizid', models.IntegerField(default=0)),
                ('quizname', models.CharField(max_length=100)),
                ('quizdate', models.DateTimeField(default='0000-00-00')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('Message_id', models.AutoField(primary_key=True, serialize=False)),
                ('classname', models.CharField(max_length=200)),
                ('author', models.CharField(default='no name', max_length=200)),
                ('content', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleName',
            fields=[
                ('roleid', models.IntegerField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('schoolid', models.IntegerField(primary_key=True, serialize=False)),
                ('schoolname', models.CharField(max_length=50)),
                ('schoolimage', models.ImageField(default='default.jpg', upload_to='')),
                ('schoolcontactno', models.IntegerField()),
                ('schooladdress', models.CharField(max_length=500)),
                ('createddate', models.DateTimeField()),
                ('schoolemail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='schoolTeacher',
            fields=[
                ('teacherid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('passowrd', models.CharField(max_length=13)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('regno', models.CharField(max_length=20)),
                ('joiningdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.IntegerField(primary_key=True, serialize=False)),
                ('regno', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contactno', models.CharField(max_length=13)),
                ('registrationdate', models.DateTimeField()),
                ('address', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=13)),
                ('imagepath', models.ImageField(default='default.jpg', upload_to='')),
                ('sectionid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TblClass',
            fields=[
                ('classid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('schoolid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubmitAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadid', models.IntegerField()),
                ('assignmnet_file', models.FileField(default='no file', upload_to='media')),
                ('submitdate', models.DateTimeField()),
                ('assignmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.assignment')),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.course')),
                ('schoolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.school')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeedBack',
            fields=[
                ('feedbackid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('submitdate', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Bad', 'Bad')], default='none', max_length=100)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.course')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.student')),
                ('teacherid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.schoolteacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='classid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.tblclass'),
        ),
        migrations.AddField(
            model_name='student',
            name='schoolid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.school'),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='classid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.tblclass'),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='schoolid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.school'),
        ),
        migrations.CreateModel(
            name='quizQuestionsAndAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionid', models.CharField(default=0, max_length=20)),
                ('question', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=20)),
                ('option2', models.CharField(max_length=20)),
                ('option3', models.CharField(max_length=20)),
                ('option4', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=20)),
                ('courseid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='teacherApp.course')),
                ('quizid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.createquiz')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lectureid', models.IntegerField(primary_key=True, serialize=False)),
                ('lecturename', models.CharField(max_length=150)),
                ('tutoriallink', models.CharField(default='No tutorial for this lecture.', max_length=100)),
                ('uploaddate', models.DateTimeField()),
                ('lecturenotes', models.FileField(default='no notes', upload_to='media')),
                ('recordedlecture', models.FileField(default='no video', upload_to='media')),
                ('lecturedescription', models.TextField(max_length=500)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.course')),
                ('schoolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.school')),
            ],
        ),
        migrations.AddField(
            model_name='createquiz',
            name='classid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.tblclass'),
        ),
        migrations.AddField(
            model_name='createquiz',
            name='courseid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='classid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.tblclass'),
        ),
        migrations.AddField(
            model_name='course',
            name='roleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.rolename'),
        ),
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(default='NULL', max_length=200)),
                ('event_details', models.CharField(default='NULL', max_length=200)),
                ('due_date', models.DateField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.tblclass')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('mark_attendance', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=50)),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.tblclass')),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.course')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.student')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='classid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.tblclass'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='courseid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='schoolid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherApp.school'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacherid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='teacherApp.schoolteacher'),
        ),
    ]
